### PR TITLE
The previous object of the removed object was defined.

### PR DESCRIPTION
**Pull request by ArslanBilal**
It is little confusing to choose right branch :/ I think this one is true :)

### CODE REVIEW

**Comment by waynewbishop** [comment]
Yeah, this is the correct structure! I'll see about merging the proposed changes sometime today.

Cheers;

**Comment by ArslanBilal** [comment]
Okay!

**Comment by waynewbishop** [comment]
Thanks again for your contribution! It would great to get your project feedback at www.waynewbishop.com/feedback.

**Comment by ArslanBilal** [comment]
Thanks!

**Pull request merged**
