### PR TITLE
Guard statements in sort algorithms

### PR DESCRIPTION
**Pull request by perlfly**
Minor changes in Sorting Tests

### CODE REVIEW

**Comment by perlfly** [comment]
As I can understand this project, it might be useful showing the intended use of guards in Swift.

**Comment by waynewbishop** [comment]
Hi Matteo;

Thanks much for the contribution! I've been meaning to incorporate examples of <code>guard</code> in the project so this is a nice addition. I also like your Swift-based enhancements for the <code>isSorted</code> helper method. 

Cheers;

-Wayne

**Comment by waynewbishop** [comment]
If you are interested obtaining [a book](http://shop.waynewbishop.com) just let me know that I can arrange to send you a free copy.

**Comment by perlfly** [comment]
Great! Really appreciate it. Hope I can contribute a little more.

**Comment by waynewbishop** [comment]
Sounds great. If you'd like to post a contact email address we can coordinate getting the book to you.

**Comment by perlfly** [comment]
I've left you a short feedback for the book. You can verify the domain is really mine.
I also left you a suggestion for an additional topic. ;-)

Thanks!

**Pull request merged**
