### PR TITLE
add count property to AVL tree

### PR DESCRIPTION
**Pull request by morganchen12**

### CODE REVIEW

**Comment by waynewbishop** [comment]
Hi Morgan; 

Thanks for following the project as well as this PR! At first glance it looks great. Hope to get around to testing in the next few days.

**Comment by morganchen12** [comment]
Updated with a swiftier solution. This is doable as a one liner

```
var count: Int {
    return (self.left?.count ?? 0) + 1 + (self.right?.count ?? 0)
}
```

but one liners aren't always the most readable. `count` can also be implemented in a breadth-first and/or iterative manner--this is just one of many possibilities.

**Comment by waynewbishop** [comment]
Hi Morgan, looks great! I finally have time to take a look at this.

**Comment by morganchen12** [comment]
🍻

**Comment by waynewbishop** [comment]
Cheers! If you haven't had a chance to get the book yet, I can see about getting you a free copy. Just let me know.

**Pull request merged**
