### PR TITLE
Code metrics improvements / code optimizations / production (readability/coupling/complexity)

### PR DESCRIPTION
**Pull request by hack2root**
LinkedList<T> optimizations:
-added counter variable
-added overflow/underflow exceptions
-moved counter to read-only property
-moved code to function nodeAtIndex function
-changed variables to optionals for readability
-removed overcompilcated code blocks
-removed Enumerable constraint for T
-removed print

LLNode<T> optimizations:
-added default init and parametrized init to LLNode<T>

Tests modifications:
-added try! code block to bypass exception handling

### CODE REVIEW

**Comment by hack2root** [comment]
Currently working at
https://github.com/hack2root/SwiftStructures/commit/50f8eded7865d9fad8e680e610d21b3bc443ff6c

My opinion that it is essential to replace spaces with tabs, because different users like different tabs on XCode [Preferences - > Text Editing -> Indentation].

I prefer 2, GitHub prefers 8, so for commits using tabs it will not overcommit the lines and extra spaces

**Comment by morganchen12** [comment]
My concern with tabs vs spaces is Xcode's default is to use spaces to indent. Either way, the precedent for tabs vs spaces shouldn't be evaluated on a case-by-case basis per PR; someone should add a style guide or contributing guide to this repo. Until then, you may want to stick with spaces since the rest of the project already uses spaces--but, if you don't, it's not such a big deal.

**Comment by morganchen12** [comment]
There's a few places ([1](https://github.com/waynewbishop/SwiftStructures/pull/66/files#diff-518157459ebd242ffa5181faea82766bR18), [2](https://github.com/waynewbishop/SwiftStructures/pull/66/files#diff-518157459ebd242ffa5181faea82766bR54)) where force-unwraps aren't necessary.

**Comment by morganchen12** [comment]
For the map and filter functions, consumers probably shouldn't have to know about the `LLNode` type.

```
func map<U>(transform: T -> U) -> LinkedList<U>
```

instead of

```
func map(formula: LLNode<T> -> T) -> LinkedList<T>
```

**Comment by morganchen12** [comment]
There are a few `defer` closures that are followed immediately by `return` statements, which seems unnecessary.

**Comment by morganchen12** [comment]
the `addLink()` and `addNode()` methods could maybe be renamed to indicate how the values are added (i.e. `append`, `prepend`), but naming is hard and verbosity can feel awkward.

**Comment by hack2root** [comment]
@morganchen12 Phanks a lot! Could you advice easy to read names for the duplicate function naming (if i understood remark correctly) for addNode, addLink functions? (i.e. append<...>, prepend<...>)? I'm not a native speaker and do not understand the mush difference and verbosity then

**Comment by morganchen12** [comment]
`addLinkAtIndex(key: index:)` could be renamed to `addValue(_: atIndex:)`, `addLink(key:)` could be renamed to `prepend(key:)`. Other than that it looks fine. Naming is also partially opinion, so you're free to propose alternatives.

**Comment by waynewbishop** [comment]
Thanks for submitting this pull request. Since this submission the code has been changed considerably. Feel free to check the latest version on `develop` if there are additional changes you'd like to see.

Regards;

**Pull request closed without merging**
